package org.example.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;
import org.example.model.Order;

/**
 * Class _IndexFund was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IndexFund extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ISIN = Property.create("isin", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<Order>> ORDERS = Property.create("orders", List.class);

    protected String isin;
    protected String name;

    protected Object orders;

    public void setIsin(String isin) {
        beforePropertyWrite("isin", this.isin, isin);
        this.isin = isin;
    }

    public String getIsin() {
        beforePropertyRead("isin");
        return this.isin;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void addToOrders(Order obj) {
        addToManyTarget("orders", obj, true);
    }

    public void removeFromOrders(Order obj) {
        removeToManyTarget("orders", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Order> getOrders() {
        return (List<Order>)readProperty("orders");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "isin":
                return this.isin;
            case "name":
                return this.name;
            case "orders":
                return this.orders;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "isin":
                this.isin = (String)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "orders":
                this.orders = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.isin);
        out.writeObject(this.name);
        out.writeObject(this.orders);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.isin = (String)in.readObject();
        this.name = (String)in.readObject();
        this.orders = in.readObject();
    }

}
